<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'first_name' => 'Shweta Kholi',
                'last_name' => null,
                'email' => 'kolishwetha21@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9654446838',
                'whatsapp_number' => '9654446838',
                'company_name' => 'Shweta Kholi',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Gaurav',
                'last_name' => 'Arora',
                'email' => 'info@goldoveresas.in',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '7017447360',
                'whatsapp_number' => '7017447360',
                'company_name' => 'Gold Overseas',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Sanjeev',
                'last_name' => 'Dhimam',
                'email' => 'admissions@planningskyeducation.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9872221885',
                'whatsapp_number' => '9872221885',
                'company_name' => 'Planning sky Education',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Manjot',
                'last_name' => 'Singh',
                'email' => 'nggec.chd@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9888690298',
                'whatsapp_number' => '9888690298',
                'company_name' => 'NGGEC',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Karthik',
                'last_name' => null,
                'email' => 'karthik.dreamabroad@gmail',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '8125124893',
                'whatsapp_number' => '8125124893',
                'company_name' => 'Dream Abroad',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Kiranpreet',
                'last_name' => null,
                'email' => 'info@hopeoverseas.in',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9888548039',
                'whatsapp_number' => '9888548039',
                'company_name' => 'Hope Overseas',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Anubal',
                'last_name' => null,
                'email' => 'agasconsultants@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '7986419936',
                'whatsapp_number' => '7986419936',
                'company_name' => 'Agas Consultants',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Bushra',
                'last_name' => null,
                'email' => 'serviceimmigrate@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9016300717',
                'whatsapp_number' => '9016300717',
                'company_name' => 'Immigrate Service',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Sarangh',
                'last_name' => null,
                'email' => 'www.dhawanconsultants.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9814861077',
                'whatsapp_number' => '9814861077',
                'company_name' => 'Dhawan education',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Ajmal',
                'last_name' => null,
                'email' => 'ajmalsha2@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '971561834369',
                'whatsapp_number' => '971561834369',
                'company_name' => 'Bird Edu',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Rohit',
                'last_name' => null,
                'email' => 'apply@ukiecglobal.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9871339575',
                'whatsapp_number' => '9871339575',
                'company_name' => 'UKIEC',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Dhanya',
                'last_name' => null,
                'email' => 'manager@casilda.in',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9746999700',
                'whatsapp_number' => '9746999700',
                'company_name' => 'Casilda',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Sihas',
                'last_name' => null,
                'email' => 'sihas@edastudy.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '7902882244',
                'whatsapp_number' => '7902882244',
                'company_name' => 'Eda study Consultancy',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Shobha',
                'last_name' => null,
                'email' => 'info@studyedwise.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9866397922',
                'whatsapp_number' => '9866397922',
                'company_name' => 'Study Edwise',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Sridhar',
                'last_name' => null,
                'email' => 'raj10@rajedu.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9866397923',
                'whatsapp_number' => '9866397923',
                'company_name' => 'Raj Consultant',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Shafeeq',
                'last_name' => null,
                'email' => 'Info@skymark.in',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '6238840117',
                'whatsapp_number' => '6238840117',
                'company_name' => 'Sky Mark Education',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Vijay',
                'last_name' => 'Saha',
                'email' => 'instavisa118@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9067696577',
                'whatsapp_number' => '9067696577',
                'company_name' => 'Insta Visa',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Amneet',
                'last_name' => 'Kaur',
                'email' => 'ukenrollments.crystalvisa@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9988928767',
                'whatsapp_number' => '9988928767',
                'company_name' => 'Crystal Overseas',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Ajmal',
                'last_name' => 'Rahim',
                'email' => 'thalassery@akbarstudy.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '8089934273',
                'whatsapp_number' => '8089934273',
                'company_name' => 'Akbar Study Abroad',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Muneer',
                'last_name' => null,
                'email' => 'muneer.studegram@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '09847142205',
                'whatsapp_number' => '09847142205',
                'company_name' => 'Studegram',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Ameen',
                'last_name' => null,
                'email' => 'aimbritz@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9747277233',
                'whatsapp_number' => '9747277233',
                'company_name' => 'Aim Britz Study Abroad',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Prasanth',
                'last_name' => null,
                'email' => 'prashanth@signupconsultancy.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '7799009570',
                'whatsapp_number' => '7799009570',
                'company_name' => 'Signup consultancy',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Vedant',
                'last_name' => null,
                'email' => 'Vedant@careerbrick.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9899286241',
                'whatsapp_number' => '9899286241',
                'company_name' => 'Career Brick Consultants',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Surrender',
                'last_name' => 'Meethu',
                'email' => 'surendrasaroj71@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '8976976897',
                'whatsapp_number' => '8976976897',
                'company_name' => 'Edument International',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Atul Kumar',
                'last_name' => 'Thakral',
                'email' => 'cieconsultantsindia@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9466588819',
                'whatsapp_number' => '9466588819',
                'company_name' => 'Crackerjack Immigration & Education Consultants',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Hitesh',
                'last_name' => 'Changotra',
                'email' => 'predusolutions@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9872656666',
                'whatsapp_number' => '9872656666',
                'company_name' => 'PR Education Solution',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Sahil',
                'last_name' => 'Sujith',
                'email' => 'sahil.sujit@hackmim.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '8224066342',
                'whatsapp_number' => '8224066342',
                'company_name' => 'HACK MIM',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Mahesh',
                'last_name' => 'Pappu',
                'email' => 'pavan@uniaway.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9178937 00330',
                'whatsapp_number' => '9178937 00330',
                'company_name' => 'Uniaway',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Ram Prasad',
                'last_name' => 'Reddy',
                'email' => 'info@studentoverseas.in',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '8790332241',
                'whatsapp_number' => '8790332241',
                'company_name' => 'Student Overseas',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Ananthya',
                'last_name' => null,
                'email' => 'anathyaya@fastglobalmigration.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '8197880292',
                'whatsapp_number' => '8197880292',
                'company_name' => 'Fast Global Migration',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Ashik',
                'last_name' => null,
                'email' => 'support@edwestedu.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9995803503',
                'whatsapp_number' => '9995803503',
                'company_name' => 'Edwest Educational consultant',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Arun',
                'last_name' => null,
                'email' => 'Educocareer01@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '7902698545',
                'whatsapp_number' => '7902698545',
                'company_name' => 'educocareer',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Sugandha',
                'last_name' => null,
                'email' => 'sugandha@albatrossgroup.in',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9815788885',
                'whatsapp_number' => '9815788885',
                'company_name' => 'albatross',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Ebin',
                'last_name' => null,
                'email' => 'info@tutorrabbitpathways.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '7012924927',
                'whatsapp_number' => '7012924927',
                'company_name' => 'Tutorrabit',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Ashik',
                'last_name' => null,
                'email' => 'Ashikmdevassy006@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '7510126526',
                'whatsapp_number' => '7510126526',
                'company_name' => 'eurohub',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'JIJY',
                'last_name' => 'GEORGE',
                'email' => 'goodhopeinternational23@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9745421621',
                'whatsapp_number' => '9745421621',
                'company_name' => 'Goodhope internatonal',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Jasleen',
                'last_name' => null,
                'email' => 'admissionsivis@gmail.com',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '7710704141',
                'whatsapp_number' => '7710704141',
                'company_name' => 'ielts2 visa',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
            [
                'first_name' => 'Gagan',
                'last_name' => null,
                'email' => 'info@foreignstudies.ac.in',
                'role' => 'Sensitive CPI( Admin Uses Only)',
                'password' => Hash::make('password'),
                'mobile_number' => '9415104574',
                'whatsapp_number' => '9415104574',
                'company_name' => 'tamec private ltd',
                'address' => 'Address not provided',
                'city' => 'City not provided',
                'post_code' => 'Post code not provided',
                'country' => 'Country not provided',
                'recruit_countries' => json_encode(['india']),
            ],
        ];

        foreach ($users as $user) {
            DB::table('users')->insert($user);
        }
    }
}
