<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'first_name' => 'Sophia Tewes',
                'last_name' => null,
                'email' => 'Perfectsteps.travels@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Perfect Steps Travels and Tours Limited',
                'address' => 'Plot 500 Area 3, Ndamela House, Garki, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Theresa Moses Adepoju',
                'last_name' => null,
                'email' => 'Dabimetravels@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Dabime Travel and Tours Ltd',
                'address' => 'Toprank Hotel Plot 652, T.O.S Benson Utako, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Albashir Baffa Yola',
                'last_name' => null,
                'email' => 'travecotravels@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Travco Travels and Tours',
                'address' => '112 Oladipo Diya Street, 900110, Midel Centre, suite 406',
                'city' => 'Not provided',
                'post_code' => '900110',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Adeyanju Samuel',
                'last_name' => null,
                'email' => 'countrytours440@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Country Tours',
                'address' => '2b, El-minya Street, Abacha Estate, Zone 4',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Not provided',
                'last_name' => null,
                'email' => 'artictravels01@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Artic Travels and Tours Ltd',
                'address' => 'Suite 6, Freezone Nigeria Immigration Service Headquaters Suaka, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Adebiyi Damilare',
                'last_name' => null,
                'email' => 'info@duwatravels.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Duwa Travels',
                'address' => '22 Road B Close Efab Estate, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Igwe Gloria Ifeoma',
                'last_name' => null,
                'email' => 'info@glowtravelsandtours.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Glow Travels and Tours Limited',
                'address' => 'Suite 1, Rear Wing(Edo House), C.B.D',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Ijeoma Emeka',
                'last_name' => null,
                'email' => 'keeinternationaleducationaleduservices@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'King E & E International Education Firm',
                'address' => 'Block A1, Shop 1 321, Road Gwarimpa, FCT, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Ogbonnaya Lilian Chioma',
                'last_name' => null,
                'email' => 'signettravels@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Signet Travels Nig Ltd',
                'address' => 'Abuja FCT Class Hotel, Wuse zone 5',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Samaul Emmanuel Ade',
                'last_name' => null,
                'email' => 'ociaoglobalservices@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Ociao Global Services',
                'address' => 'Plot 16, behind NAWA complex Kado',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Alhassan Zainab',
                'last_name' => null,
                'email' => 'hhtravelservicesltd@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'H.H Travel Services LTD',
                'address' => 'Suite 31 Yasuha Plaza Wuse 2, Abj',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Tina Oghenekaro Ubiokor',
                'last_name' => null,
                'email' => 'quinaulogistics@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Quinau Travels & Tours',
                'address' => 'Wuse zone 4, 3rd floor, Abj',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'AKINBAMI OLAWALE IBRAHIM',
                'last_name' => null,
                'email' => 'akinbamiwale2781@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Fkhalifa Travel Consult',
                'address' => '2,Sesidairo Street,Oluwo Onikolobo Abeokuta,Ogun State',
                'city' => 'Abeokuta',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Amos Ukwile Edime',
                'last_name' => null,
                'email' => 'info@kindredtravels.com.ng',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Kindred Travels and Tours Ltd',
                'address' => '313 Usuma Street, Maitama, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Ndulaka Godson Chukwuka',
                'last_name' => null,
                'email' => 'Zibahworldtravels@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'ZibahWorld Logiatica Travels and Tours Ltd',
                'address' => 'Suite B55 H&A Plaza, Plot 697 Idris Gidado Street, Wuye District, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Margaret Aniara',
                'last_name' => null,
                'email' => 'panacheluxglobal@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Panachelux Travels & Tour',
                'address' => '3rd floor Niconn plaza, CBD',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Oba Ademola',
                'last_name' => null,
                'email' => 'afotintegratedservicesltd@yahoo.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Afot Integrated Services Ltd',
                'address' => '18 Ebitu Ukiwe Street, Jabi',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Ogbomon Saviour-Alens',
                'last_name' => null,
                'email' => 'info@agsatechglobal.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Agsatech Global Nig Ltd',
                'address' => 'Suite 1, Eterna Petrol Aviation Before Airport Gate, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Onoh Grace Makuwchukwu',
                'last_name' => null,
                'email' => 'info@tourism.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'TBS International Company',
                'address' => 'No 13, Zaria Street Garki, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Nurudeen Alade',
                'last_name' => null,
                'email' => 'mcieducation2004@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'MCI Multi education Limited',
                'address' => '1, AJIRAN STREET, AGUNGI LAGOS',
                'city' => 'Lagos',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'DR. HENRY NWAKUNOR',
                'last_name' => null,
                'email' => 'Henrynwakunor@yahoo.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'EL-SHADDAI COMMUNICATIONS AND INVESTMENT LIMITED',
                'address' => 'HANOCO PLAZA 113, IKORODU FADEYI, LAGOS',
                'city' => 'Lagos',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Opara Udoka Chima',
                'last_name' => null,
                'email' => 'airgroovetravels13@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Airgroove Travels and Tours Ltd',
                'address' => 'Triple Tee Plaza,2nd floor, suite 15, Garki 2, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Mr Collins Ebenezer Adigwe',
                'last_name' => null,
                'email' => 'ejecegets@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Ejece Global Energy and Travels',
                'address' => 'opp Gudu Market, MKK Plaza, Suite 514',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'DR(MRS) SARAH JOHN ETUKUDO',
                'last_name' => null,
                'email' => 'sarajohnng@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Sarahjohn Nig LTD',
                'address' => 'FF6 West Logon Plaza, Karu',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Lami Isiaka Semirah',
                'last_name' => null,
                'email' => 'haretravelsandtours@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Hare Travels and Tours Ltd',
                'address' => 'Suite C7 lpent 7 Estate Plaza Kasana, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Janechelsea Chioma Sopurum',
                'last_name' => null,
                'email' => 'laannatravelsandtoursltd@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => "La'anna Travels and Tours Ltd",
                'address' => '9, Idimba Street, Wuse Zone 3, Tamara Guest Inn, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Dr. Tony Ajaino',
                'last_name' => null,
                'email' => 'ajainotony@gmail.com',
                'role' => 'Probable Channel Partner',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'VWONACO VENTURES INTERNATIONAL',
                'address' => 'Benin City, Edo state',
                'city' => 'Benin City',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Micheal Onuwa',
                'last_name' => null,
                'email' => 'Lidseasy@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Lidseasyplay Global Travels and Logistics',
                'address' => 'B108 Zitel Plaza Opp Daily Trust Newspaper, Jabi, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Ibrahim Muhammad Jamiu',
                'last_name' => null,
                'email' => 'sofatotravels@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Sofato Travels and Tours',
                'address' => 'HS 29, 4th Avenue, Opp Mr Biggs, Lugbe FCT,Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Abdulmalue Hassan',
                'last_name' => null,
                'email' => 'famaktravels@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Famak Travels and Tours Ltd',
                'address' => 'Plot 479 Ken Nnamain Cr. Wuye, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Abdulmarof Abdulaziz',
                'last_name' => null,
                'email' => 'allahulmustaantravels23@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Allahulmistaan Logistics T.T Ltd',
                'address' => 'Franklys Street Cmd Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Gbenga Olawumi',
                'last_name' => null,
                'email' => 'traveltime_limited@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Travel Time and Tours Synergy Ltd',
                'address' => '1st Floor Silverbird Galleria CBD, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Ijeh Christopher Chinedu/Ijeh Celestine',
                'last_name' => null,
                'email' => 'cal2fly@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Cal2fly Ltd',
                'address' => 'Aes Apartment nd Suite, Plot 1118, Jabi Airport,Adj Citech',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Egerue Sharon Ijeoma',
                'last_name' => null,
                'email' => 'shietravelltd@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Shie Travels Limited',
                'address' => '006 Aliyu Modibbo Strt, Asokoro',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Mfon Akpan',
                'last_name' => null,
                'email' => 'fonwingstravels695@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'FON-Wings Global Travels and Tours',
                'address' => 'House of Representative Extention',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Mujtaga ica',
                'last_name' => null,
                'email' => 'info@travelplaceng.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'The Travel Place Ltd',
                'address' => '5 Usuma Close, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Issa Jamiu Muhammad',
                'last_name' => null,
                'email' => 'alwaseelatravelsltd@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Al-Waseelat Travels and Tours Ltd',
                'address' => 'Plot C4, Amsalco Plaza, Plot 862(New Plot 9), Dunukofia Street, Area 11, Garki,Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Joan Ulaeto',
                'last_name' => null,
                'email' => 'info@hojtravels.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'HOJ Travels and Tours Ltd',
                'address' => 'Sco3 Kingfem Plaza, Mabushi, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Raymond Nkata',
                'last_name' => null,
                'email' => 'info@greenwichtravels.com.ng',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Greenwich Gap Services Ltd',
                'address' => '14 Borno Str, Area 10, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Chioma Hope Oleru',
                'last_name' => null,
                'email' => 'hotianaglobaltravelandtour@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Hotiana Global Travel and Tours Ltd',
                'address' => 'Plot 102 CBN Choos Estate, Apo',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Peace c.Iyare',
                'last_name' => null,
                'email' => 'bookings@peacefulskytravel.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Peaceful Sky Travels and Tours Ltd',
                'address' => '41, Ajose Adeogun Street, Utako District, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Oketta Etsenamhe Vivian',
                'last_name' => null,
                'email' => 'timvividtravels@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Timvivid Travels and Tours Ltd',
                'address' => 'Suite 267 Obasanjo block Garki , ultra modern complex  . Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Sulaiman Mashood A',
                'last_name' => null,
                'email' => 'mrsa220@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Naib-Marid Travels and Tours Ltd',
                'address' => 'Suite b9&b10 Royal Plaza, No 12 Fria Close off Ademola Adetokunbo Cr, Wuse 2',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Odim Judith',
                'last_name' => null,
                'email' => 'jodintravelsandtoursltd@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Jodin Travels and Tours Ltd',
                'address' => 'Suite FF25, Anafana Plaza, 1st Avenue Gwarimpa',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Edache Gift',
                'last_name' => null,
                'email' => 'edache.gift@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Valojroyal Travels and Tours Ltd',
                'address' => 'Fudi Mall Jabi, Opposite Chida Hotel',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Udekaogu Faith',
                'last_name' => null,
                'email' => 'faith@karrygo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Karrygo.com Ltd',
                'address' => 'Suite 203 No 16, Ademola Adetokunbo Crescent Wuse 2',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Chinenyenwa Nnamuchi',
                'last_name' => null,
                'email' => 'asogworldtravels@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Asogworld Travel and Tours Ltd',
                'address' => 'Suite FF 25 Anafara Plaza',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Dominic Victoria',
                'last_name' => null,
                'email' => 'toruyadgadavec@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Toriyad Gadavee Ltd',
                'address' => 'Maitama Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Maduadi Chioma',
                'last_name' => null,
                'email' => 'travelwahala@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Travel Wahala and Tours Limited',
                'address' => 'Office Space Work and Connect, Jabi',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Basil O. Amuno',
                'last_name' => null,
                'email' => 'skydovetravels@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Skydove Travels and Tours Ltd',
                'address' => 'Portakabin 3c Beside Annex1, National Assembly Complex, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Dada Iyabode',
                'last_name' => null,
                'email' => 'airfieldtravelsandtours@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Airfield Travels',
                'address' => 'Obum Plaza',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Evelyn Ogeyi Sleve-Ogar',
                'last_name' => null,
                'email' => 'travelsoptions@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Wellcome Travels & Tours Ltd',
                'address' => '7, Gaidam Close, Area 8, Garki, Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Esther Oniella Ademola',
                'last_name' => null,
                'email' => 'seamejetickets@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Seamej Travels and Tours Ltd',
                'address' => 'Plot 266, Mortgage House Cadastral AO, CBD, Abuja(By Ceddi Plaza)',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Esther Abimbola',
                'last_name' => null,
                'email' => 'enttravel27@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'E.N.T Travels',
                'address' => 'No 14 D Crescent Citec Estate',
                'city' => 'Not provided',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Elechi Victoria',
                'last_name' => null,
                'email' => 'latoriatravels2023@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Latoria Cooperate Services Limited',
                'address' => '25 Limpopo Street, Maitama,Abuja',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Uhunamure Jacinta Erhahon',
                'last_name' => null,
                'email' => 'bookings@brisktravels.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Brisk Marketing and Travels Limited/Brisk Travels',
                'address' => 'Suite 13 Shalom Plaza, Gudu Abuja/ 124, City Road London',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'James Jennifer',
                'last_name' => null,
                'email' => 'melstartravels2000@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Melstar Travels & Tours LTD',
                'address' => 'SF 04 2nd FL, Hatlab plaza Wuse',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Aro Mary',
                'last_name' => null,
                'email' => 'tranquilanetravels@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Tranquilane Travels & Global Services',
                'address' => 'T-PUMPY Estate phase 6, Lugbe',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Okunola Basirat',
                'last_name' => null,
                'email' => 'sales@basoltravels.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Basol Travels & Tour LTD',
                'address' => 'Suite 304 GCL Plaza Wuse 2 Abj',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Akor Otobo',
                'last_name' => null,
                'email' => 'diptrata@yahoo.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Diplomat Travels&Tourism Agency',
                'address' => 'Left wing 2nd fl, millenium plaza,Abj',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Awodo Emeka Daniel',
                'last_name' => null,
                'email' => 'flyeagleglobalairline@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Eagle Global Express Airline LTD',
                'address' => 'No.5 Sokodo Cr, Wuse zone 5',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Adeiza Yisa',
                'last_name' => null,
                'email' => 'c.cadatravelsltd@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'C.Cada Travels LTD',
                'address' => 'Suite B203 Soar plaza, 1st Ave. Gwarn',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Okoye Chinenye',
                'last_name' => null,
                'email' => 'tickets@lyciatravels.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Lycia Travels & Tours LTD',
                'address' => 'No 1042 Ekiti House CBD, Abj',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Mr Igbinosa Olaye',
                'last_name' => null,
                'email' => 'noneldantravels@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Noneldan Travels LTD',
                'address' => 'No.5 Fingesi st Utako, Abj',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Aigbodion Lawrenta Ehi',
                'last_name' => null,
                'email' => 'aeromilestravels13@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Aeromiles Travels & Tours Nig',
                'address' => 'Flat 1, Block A,Sky Memorial Plaza,Wuse',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Josephine N. Adzor',
                'last_name' => null,
                'email' => 'support@newgold22travels.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Newgold22 Travels & Tour',
                'address' => 'Suite C10 Silverline Plaza Garki 11',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Onyeka Okwudili Johnbosco',
                'last_name' => null,
                'email' => 'skyfirmtravels@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Skyfirm Travels LTD',
                'address' => 'Suite 23-24 Habiba Plaza Wuse 2',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Iyabo Oladeji',
                'last_name' => null,
                'email' => 'agesworldtravelsltd@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Ages-world Travels & Tour LTD',
                'address' => 'No.27 Bangul st wuse 2, Abj',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
            [
                'first_name' => 'Ukamaka Egbo',
                'last_name' => null,
                'email' => 'ukamakaegbo@gmail.com',
                'role' => 'SENSITIVE CPI( ADMIN USES ONLY)',
                'password' => Hash::make('password'),
                'mobile_number' => 'Not provided',
                'whatsapp_number' => 'Not provided',
                'company_name' => 'Splashland Travel Tours & Logistics Ltd',
                'address' => 'Suite G1,9/fl Alibro Plaza, Utako',
                'city' => 'Abuja',
                'post_code' => 'Not provided',
                'country' => 'Nigeria',
                'recruit_countries' => json_encode(['nigeria']),
            ],
        ];

        foreach ($users as $user) {
            // Check if the email already exists in the database
            if (!DB::table('users')->where('email', $user['email'])->exists()) {
                DB::table('users')->insert($user);
            }
        }
    }
}
