name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master # Ensure this is the correct branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_KEY }}

      - name: Echo SSH public key for debugging
        run: |
          echo "$SSH_AUTH_SOCK"
          ssh-add -L

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            cd /var/www/html  # Corrected path
            git pull origin master  # Ensure this matches your branch name
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            # Restart PHP FPM or any other required services
          EOF
