name: Deploy Laravel App

on:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Pull latest changes
        run: git pull origin master

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install npm dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: |
            .
            !node_modules
            !tests
            !vendor

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: [AFRICA, BANGLADESH]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app-build

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets[format('HOST_{0}', matrix.server)] }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_KEY }}
          script: |
            cd /var/www/html
            git pull
            php artisan optimize:clear
            composer install --no-dev --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize
            # Remove npm ci and npm run build from here
