name: Deploy Laravel Project

on:
  push:
    branches:
      - main # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy to Server
        env:
          SSH_USER: username
          SSH_HOST: your_server_ip
          SSH_PATH: /var/www/your_project # Path to your Laravel project on the server
        run: |
          ssh $SSH_USER@$SSH_HOST "
            cd $SSH_PATH &&
            git pull origin main &&
            composer install --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan cache:clear &&
            php artisan config:cache &&
            php artisan route:cache
          "
